services:
  bot_api:
    container_name: bot_api
    build: .
    restart: unless-stopped
    volumes:
      - .:/app
    ports:
      - 9052:80
    command: ["python", "/app/bot/manage.py", "runserver", "0:80"]
    environment:
      DEBUG: 'True'
